### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [pearmans/project6#1]
One of the few projects I haven't been able to immediately break! While it does work though, I do see some inconsistent indentation in `index.erb` and hard-tabs instead of soft-tabs in `app.rb` that I'd like you to fix. The [resources on this page](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) should be helpful here.

Let me know if you encounter any difficulties and I'll be happy to hop on a screenshare!

**Comment by stuartpearman** [comment]
I think I have my indentation right now. I have one question though. I know
that indentation is pretty important in ruby, but when using embedded ruby
in my html, I never know the proper way to indent a multi-line ruby block.
Usually I only need to do inline snippets, but here's an example.

<div>
>   <% for @something.each do
>     if @something['attr'] do  %>
>       <p>some text</p>
>     <% end
>   end %>
> </div>

I know that is a lame example.

Also relevant... Do you use a gmail syntax highlighter of any kind?

**Comment by chrisvfritz** [comment]
`index.erb` is looking great! `app.rb` still looks like it's using tab characters instead of two-space indention though. The indentation doesn't actually affect how the Ruby runs (like it does in Python). I simply enforce it because it's A) nicer for me to read with consistent indentation and B) a lot easier to get a great job with professional-looking indentation.

For multiple consecutive lines of indentation, there's isn't a community-wide standard, but I personally like to wrap each line separately, even for multiple consecutive lines of Ruby. For example:

``` erb
<div>
  <% @something.each do |thing| %>
     <% if thing['attr'] %>
       <p>some text</p>
     <% end %>
  <% end %>
</div>
```

For these code blocks, I don't use a syntax highlighter or anything else for Gmail. I'm not even sure if such a thing exists, though it might. I'm actually writing this on GitHub, using [GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks).

**Comment by stuartpearman** [comment]
I updated the app.rb to be soft tabs. I kept 4 space hard tabs on certain
files, like style.css, is it frowned upon to have different indentation
throughout your files? For Sass especially I like the 4 space, hard tab
formatting.

**Comment by chrisvfritz** [comment]
:+1: Excellent. 

Different indentation in different files is fine, though my personal preference is to use two-space soft-tabs for everything. My rule for the class is if the file _only_ contains Ruby, it should be two-space soft-tabs, since it's the undisputed standard for that language. There are some Rubyists (though they are rare) that choose different spacing and use hard-tabs instead, but one of my goals is to make students in this class as hirable as possible, and some companies simply wouldn't hire you if they saw Ruby code not using two-space soft-tabs.

Ruby is unusual though. In HTML, CSS, and JavaScript, there's not an industry standard that all the big players agree to. So the only thing I care about for non-Ruby files is consistency. That means A) no mixing of soft-tabs and hard-tabs, and B) keep everything well-indented. There are [some who disagree with point A](http://stackoverflow.com/questions/9446109/soft-tabs-or-hard-tabs#answer-15010302) and I actually agree with those people that using hard-tabs for indentation and spaces for alignment is technically ideal, but I think trying to implement that kind of policy across a team would be difficult. Devs have enough to think about.

For SASS in particular, alignment is a non-issue, so there's no downside to hard-tabs. With CSS or SCSS however, where aesthetic alignment is common (see below for example), I would strongly recommend using soft-tabs to avoid accidentally mixing tab characters with spaces for unintended side effects on other developers. Like I said though, I'll be OK with whatever in non-Ruby files, as long as it's consistent.

``` css
.facebook { background: #123456; }
.google   { background: #234567; }
.twitter  { background: #345678; }
.tumblr   { background: #456789; }
```

Does that make sense?
